# Generated by Django 5.2.13 on 2026-04-26 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionSummaryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coverage_start', models.DateField()),
                ('coverage_end', models.DateField()),
                ('structured_state_json', models.JSONField(default=dict)),
                ('narrative_markdown', models.TextField(default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('complete', 'Complete'), ('incomplete', 'Incomplete')], default='draft', max_length=20)),
                ('last_source_event_happened_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary_state', to='patients.admission')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SummaryRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('generate', 'Generate'), ('update', 'Update'), ('regenerate', 'Regenerate')], max_length=20)),
                ('target_end_date', models.DateField()),
                ('pinned_cutoff_happened_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('current_chunk_index', models.IntegerField(default=0)),
                ('total_chunks', models.IntegerField(default=0)),
                ('error_message', models.TextField(default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_runs', to='patients.admission')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summary_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_sr_status_created')],
            },
        ),
        migrations.CreateModel(
            name='SummaryRunChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('window_start', models.DateField()),
                ('window_end', models.DateField()),
                ('attempt_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error_message', models.TextField(default='')),
                ('input_event_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='summaries.summaryrun')),
            ],
            options={
                'ordering': ['chunk_index'],
                'constraints': [models.UniqueConstraint(fields=('run', 'chunk_index'), name='uq_src_run_chunk')],
            },
        ),
        migrations.CreateModel(
            name='AdmissionSummaryVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_index', models.IntegerField()),
                ('coverage_start', models.DateField()),
                ('coverage_end', models.DateField()),
                ('structured_state_json', models.JSONField(default=dict)),
                ('narrative_markdown', models.TextField(default='')),
                ('changes_json', models.JSONField(default=dict)),
                ('uncertainties_json', models.JSONField(default=dict)),
                ('evidences_json', models.JSONField(default=list)),
                ('llm_provider', models.CharField(default='', max_length=50)),
                ('llm_model', models.CharField(default='', max_length=100)),
                ('prompt_version', models.CharField(default='', max_length=50)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_versions', to='patients.admission')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='summaries.summaryrun')),
                ('summary_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='summaries.admissionsummarystate')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['admission', '-created_at'], name='idx_sv_admission_created'), models.Index(fields=['run', 'chunk_index'], name='idx_sv_run_chunk')],
            },
        ),
    ]
