# Generated by Django 5.2.13 on 2026-05-03 19:47

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        ('summaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SummaryPipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('generate', 'Generate'), ('update', 'Update'), ('regenerate', 'Regenerate')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('partial', 'Partial'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('phase1_reused', models.BooleanField(default=False)),
                ('phase1_cost_total', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=12)),
                ('phase2_cost_total', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('error_message', models.TextField(default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pipeline_runs', to='patients.admission')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SummaryPipelineStepRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_type', models.CharField(choices=[('phase1_canonical', 'Phase 1 — Canonical'), ('phase2_render', 'Phase 2 — Render')], max_length=30)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='running', max_length=20)),
                ('provider_name', models.CharField(default='', max_length=50)),
                ('model_name', models.CharField(default='', max_length=100)),
                ('base_url', models.CharField(default='', max_length=500)),
                ('prompt_version', models.CharField(default='', max_length=50)),
                ('prompt_text_snapshot', models.TextField(default='')),
                ('request_payload_json', models.JSONField(default=dict)),
                ('response_payload_json', models.JSONField(default=dict)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('cached_tokens', models.IntegerField(default=0)),
                ('cost_input', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=12)),
                ('cost_output', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=12)),
                ('cost_total', models.DecimalField(decimal_places=6, default=Decimal('0.00'), max_digits=12)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_runs', to='summaries.summarypipelinerun')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='summarypipelinerun',
            index=models.Index(fields=['status', 'created_at'], name='idx_spr_status_created'),
        ),
        migrations.AddIndex(
            model_name='summarypipelinesteprun',
            index=models.Index(fields=['pipeline_run', 'step_type'], name='idx_spsr_run_type'),
        ),
    ]
