# Generated by Django 5.2.13 on 2026-05-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0002_add_pipeline_traceability'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(default='USD', max_length=3)),
                ('quote_currency', models.CharField(default='BRL', max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('reference_date', models.DateField()),
                ('provider', models.CharField(max_length=50)),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-reference_date'],
                'indexes': [models.Index(fields=['reference_date'], name='idx_ers_ref_date')],
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'quote_currency', 'reference_date'), name='uq_ers_currency_date')],
            },
        ),
    ]
