# Generated by Django 5.2.13 on 2026-05-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0004_add_user_prompt_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryrun',
            name='phase2_config_json',
            field=models.JSONField(default=dict),
        ),
    ]
