# Generated by Django 5.2.13 on 2026-05-04 14:07

from django.db import migrations


def remove_phase2_api_key(apps, schema_editor):
    """Strip ``phase2_api_key`` from all existing ``SummaryRun`` records.

    This ensures no API key remains persisted in the database from
    tainted records (STP-S7-F1 era, before the fix).
    """
    SummaryRun = apps.get_model("summaries", "SummaryRun")
    updated = 0
    for run in SummaryRun.objects.exclude(phase2_config_json={}):
        config = run.phase2_config_json or {}
        if "phase2_api_key" in config:
            del config["phase2_api_key"]
            run.phase2_config_json = config
            run.save(update_fields=["phase2_config_json"])
            updated += 1


class Migration(migrations.Migration):

    dependencies = [
        ("summaries", "0005_add_summary_run_phase2_config"),
    ]

    operations = [
        migrations.RunPython(
            remove_phase2_api_key,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
