# Generated by Django 5.2.13 on 2026-05-06 01:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0006_remove_phase2_api_key_from_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarypipelinesteprun',
            name='cost_is_reported',
            field=models.BooleanField(default=False, help_text='True when cost_usd_reported comes from the provider.'),
        ),
        migrations.AddField(
            model_name='summarypipelinesteprun',
            name='cost_usd_estimated',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Token-based cost estimate (always computed for audit).', max_digits=12),
        ),
        migrations.AddField(
            model_name='summarypipelinesteprun',
            name='cost_usd_reported',
            field=models.DecimalField(decimal_places=6, default=Decimal('0.00'), help_text='Provider-reported cost in USD. 0 when provider omits cost.', max_digits=12),
        ),
    ]
