# Generated by Django 5.2.13 on 2026-05-06 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0008_add_version_cost_provenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='summarypipelinerun',
            name='summary_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pipeline_runs', to='summaries.summaryrun'),
        ),
    ]
