# Generated by Django 5.2.13 on 2026-05-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summaries', '0009_add_pipeline_run_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='summaryrun',
            name='pipeline_type',
            field=models.CharField(choices=[('serial', 'Serial'), ('parallel', 'Parallel')], db_index=True, default='serial', max_length=20),
        ),
    ]
