# Generated by Django 5.2.13 on 2026-04-25 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(help_text='Timestamp when this census run was captured')),
                ('setor', models.CharField(help_text='Sector/ward name as it appears in the source system', max_length=255)),
                ('leito', models.CharField(help_text='Bed identifier (e.g. I10CA, CV01A)', max_length=50)),
                ('prontuario', models.CharField(blank=True, default='', help_text='Patient record number (empty for non-occupied beds)', max_length=255)),
                ('nome', models.CharField(blank=True, default='', help_text='Patient name or bed status label (e.g. DESOCUPADO, RESERVA INTERNA)', max_length=512)),
                ('especialidade', models.CharField(blank=True, default='', help_text='Medical specialty abbreviation (e.g. NEF, CIV, PED)', max_length=100)),
                ('bed_status', models.CharField(choices=[('occupied', 'Ocupado'), ('empty', 'Vago'), ('maintenance', 'Em Manutenção'), ('reserved', 'Reservado'), ('isolation', 'Isolamento')], help_text='Classified bed status', max_length=20)),
                ('ingestion_run', models.ForeignKey(blank=True, help_text='Optional link to the ingestion run that produced this snapshot', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='census_snapshots', to='ingestion.ingestionrun')),
            ],
            options={
                'verbose_name': 'Census Snapshot',
                'verbose_name_plural': 'Census Snapshots',
                'ordering': ['-captured_at', 'setor', 'leito'],
                'indexes': [models.Index(fields=['captured_at'], name='census_captured_idx'), models.Index(fields=['setor'], name='census_setor_idx'), models.Index(fields=['prontuario'], name='census_pront_idx'), models.Index(fields=['captured_at', 'bed_status'], name='census_capt_bstat_idx')],
            },
        ),
    ]
