# Generated by Django 5.1.2 on 2026-05-12 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_code",
                    models.CharField(
                        help_text="Numeric unit code from source system (e.g. '640').",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Unit display name (e.g. '01 6 - 1A - CIRURGIA GERAL - HGRS').",
                        max_length=255,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Ward",
                "verbose_name_plural": "Wards",
                "ordering": ["source_code"],
            },
        ),
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Bed identifier (e.g. '101AA', 'UC01A').",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Status code from source system (meaning TBD).",
                        max_length=20,
                    ),
                ),
                (
                    "accommodation",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Accommodation type (e.g. 'ENFERMARIA', 'UTI').",
                        max_length=100,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="True if Ativo='A', False if Ativo='I'.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "ward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="beds",
                        to="census.ward",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bed",
                "verbose_name_plural": "Beds",
                "ordering": ["ward", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=["ward", "code"],
                        name="uq_bed_ward_code",
                    ),
                ],
            },
        ),
    ]
