# Generated by Django 5.2.13 on 2026-05-13 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0002_ward_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='censussnapshot',
            name='setor_codigo',
            field=models.CharField(blank=True, default='', help_text="Numeric ward code from the source system (e.g. '640').", max_length=50),
        ),
    ]
