# Generated by Django 5.2.13 on 2026-05-14 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0003_censussnapshot_setor_codigo'),
        ('ingestion', '0004_add_batch_retry_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialCensusRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Census date this record refers to')),
                ('raw_data', models.JSONField(blank=True, default=dict, help_text='Raw fields from the official census file.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion_run', models.ForeignKey(blank=True, help_text='Ingestion run that produced this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='official_census_records', to='ingestion.ingestionrun')),
            ],
            options={
                'verbose_name': 'Official Census Record',
                'verbose_name_plural': 'Official Census Records',
                'ordering': ['-date', 'id'],
                'indexes': [models.Index(fields=['date'], name='off_census_date_idx')],
            },
        ),
    ]
