# Generated by Django 5.2.13 on 2026-05-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0004_officialcensusrecord'),
        ('ingestion', '0004_add_batch_retry_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialcensusrecord',
            name='raw_data',
        ),
        migrations.AddField(
            model_name='officialcensusrecord',
            name='area_funcional',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='officialcensusrecord',
            name='cid',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='officialcensusrecord',
            name='data_internacao',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='officialcensusrecord',
            name='descricao',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='officialcensusrecord',
            name='especialidade',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='officialcensusrecord',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='officialcensusrecord',
            name='prontuario',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='officialcensusrecord',
            name='quarto_leito',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='officialcensusrecord',
            name='sigla',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='officialcensusrecord',
            name='tempo_internacao',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='officialcensusrecord',
            name='unidade',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddIndex(
            model_name='officialcensusrecord',
            index=models.Index(fields=['prontuario'], name='off_census_pront_idx'),
        ),
    ]
