# Generated by Django 5.2.13 on 2026-05-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0005_remove_officialcensusrecord_raw_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='censussnapshot',
            name='data_internacao',
            field=models.CharField(blank=True, default='', help_text='Admission date from the census table (DD/MM or DD/MM/AAAA)', max_length=20),
        ),
        migrations.AddField(
            model_name='censussnapshot',
            name='tempo_internacao',
            field=models.IntegerField(blank=True, help_text='Length of stay in days from the census table (numeric)', null=True),
        ),
    ]
