# Generated by Django 5.2.13 on 2026-05-16 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0006_add_data_internacao_tempo_internacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Specialty abbreviation (e.g. CIV, NEF, CAR)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full specialty name (e.g. CIRURGIA VASCULAR)', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
                'ordering': ['code'],
            },
        ),
    ]
