# Generated by Django 5.2.13 on 2026-05-29 20:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0012_increase_tipo_alta_length'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_date', models.DateField(help_text='Data da movimentação (do censo)')),
                ('sector', models.CharField(help_text='Setor atual', max_length=255)),
                ('bed', models.CharField(blank=True, default='', max_length=50)),
                ('origin', models.CharField(blank=True, default='', help_text='Setor de origem (campo Origem do censo)', max_length=100)),
                ('discharge_type', models.CharField(blank=True, default='', help_text='Tipo de alta (vazio = ativo)', max_length=50)),
                ('sequence', models.IntegerField(default=0, help_text='Ordem cronológica dentro da admissão')),
                ('first_seen_at', models.DateTimeField(help_text='Primeiro snapshot que capturou este estado')),
                ('last_seen_at', models.DateTimeField(help_text='Último snapshot (atualizado a cada repetição)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='patients.admission')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='patients.patient')),
            ],
            options={
                'verbose_name': 'Patient Movement',
                'verbose_name_plural': 'Patient Movements',
                'ordering': ['patient', 'sequence'],
                'indexes': [models.Index(fields=['sector', 'last_seen_at'], name='census_pati_sector_d8ac20_idx'), models.Index(fields=['patient', 'sequence'], name='census_pati_patient_385b4a_idx'), models.Index(fields=['discharge_type'], name='census_pati_dischar_f74f65_idx')],
                'constraints': [models.UniqueConstraint(fields=('patient', 'movement_date', 'sector'), name='uq_patient_movement_date_sector')],
            },
        ),
    ]
