# Generated by Django 5.2.13 on 2026-08-16 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0013_patientmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityCatalogVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateField(help_text='First local calendar date (America/Bahia) this catalog applies', unique=True)),
                ('source_reference', models.CharField(help_text='Human-readable provenance of the published document', max_length=255)),
                ('source_sha256', models.CharField(help_text='SHA-256 of the input JSON document', max_length=64)),
                ('schema_version', models.CharField(help_text='Version of the catalog document schema', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Capacity Catalog Version',
                'verbose_name_plural': 'Capacity Catalog Versions',
                'ordering': ['effective_from'],
            },
        ),
        migrations.CreateModel(
            name='CapacityGroupDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_key', models.CharField(help_text='Official identity of the sector series within the version', max_length=100)),
                ('display_name', models.CharField(help_text='Official display name resolved at publication time', max_length=255)),
                ('official_capacity', models.PositiveIntegerField(blank=True, help_text='Official capacity; null only for unrated groups', null=True)),
                ('calculation_policy', models.CharField(choices=[('standard', 'Standard'), ('linked_slots_pending', 'Linked slots pending'), ('unrated', 'Unrated')], help_text='How occupancy is calculated for this group', max_length=30)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='census.capacitycatalogversion')),
            ],
            options={
                'verbose_name': 'Capacity Group Definition',
                'verbose_name_plural': 'Capacity Group Definitions',
                'ordering': ['catalog', 'stable_key'],
            },
        ),
        migrations.CreateModel(
            name='CapacitySectorMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_code', models.CharField(help_text='Numeric source code from the legacy system census', max_length=50)),
                ('configured_source_name', models.CharField(help_text='Sector name configured for this code in this version', max_length=255)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='census.capacitycatalogversion')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='census.capacitygroupdefinition')),
            ],
            options={
                'verbose_name': 'Capacity Sector Membership',
                'verbose_name_plural': 'Capacity Sector Memberships',
                'ordering': ['catalog', 'source_code'],
            },
        ),
        migrations.AddConstraint(
            model_name='capacitygroupdefinition',
            constraint=models.UniqueConstraint(fields=('catalog', 'stable_key'), name='uq_capacity_group_catalog_stable_key'),
        ),
        migrations.AddConstraint(
            model_name='capacitygroupdefinition',
            constraint=models.CheckConstraint(condition=models.Q(('official_capacity__gt', 0), ('official_capacity__isnull', True), _connector='OR'), name='ck_capacity_group_capacity_positive_or_null'),
        ),
        migrations.AddConstraint(
            model_name='capacitygroupdefinition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('calculation_policy', 'unrated'), ('official_capacity__isnull', True)), models.Q(('calculation_policy__in', ['standard', 'linked_slots_pending']), ('official_capacity__gt', 0)), _connector='OR'), name='ck_capacity_group_policy_capacity'),
        ),
        migrations.AddConstraint(
            model_name='capacitysectormembership',
            constraint=models.UniqueConstraint(fields=('catalog', 'source_code'), name='uq_capacity_member_catalog_source_code'),
        ),
    ]
