# Generated by Django 5.2.13 on 2026-08-16 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0014_capacity_catalog'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='capacitygroupdefinition',
            name='ck_capacity_group_policy_capacity',
        ),
        migrations.AddConstraint(
            model_name='capacitygroupdefinition',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('calculation_policy', 'unrated'), ('official_capacity__isnull', True)), models.Q(('calculation_policy__in', ['standard', 'linked_slots_pending']), ('official_capacity__gt', 0), ('official_capacity__isnull', False)), _connector='OR'), name='ck_capacity_group_policy_capacity_v2'),
        ),
    ]
