# Generated by Django 5.2.13 on 2026-08-16 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0015_fix_capacity_catalog_constraints'),
        ('ingestion', '0005_add_worker_heartbeat'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupancyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField()),
                ('local_date', models.DateField()),
                ('algorithm_version', models.CharField(max_length=30)),
                ('observed_sector_count', models.PositiveIntegerField()),
                ('capacity_covered_sector_count', models.PositiveIntegerField()),
                ('calculable_sector_count', models.PositiveIntegerField()),
                ('known_capacity', models.PositiveIntegerField()),
                ('calculable_capacity', models.PositiveIntegerField()),
                ('occupied_for_rate', models.PositiveIntegerField()),
                ('occupancy_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('exceeded_by', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='occupancy_measurements', to='census.capacitycatalogversion')),
                ('census_run', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='occupancy_measurement', to='ingestion.ingestionrun')),
            ],
            options={
                'verbose_name': 'Occupancy Measurement',
                'verbose_name_plural': 'Occupancy Measurements',
                'ordering': ['captured_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='OccupancyGroupMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_key', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=255)),
                ('calculation_policy', models.CharField(blank=True, default='', max_length=30)),
                ('calculation_status', models.CharField(choices=[('calculated', 'Calculated'), ('linked_slots_pending', 'Linked slots pending'), ('unrated', 'Unrated'), ('unmapped', 'Unmapped')], max_length=30)),
                ('official_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('occupied_count', models.PositiveIntegerField(blank=True, null=True)),
                ('occupancy_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('exceeded_by', models.PositiveIntegerField(blank=True, null=True)),
                ('status_counts_json', models.JSONField(default=dict)),
                ('components_json', models.JSONField(default=list)),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='census.occupancymeasurement')),
            ],
            options={
                'verbose_name': 'Occupancy Group Measurement',
                'verbose_name_plural': 'Occupancy Group Measurements',
                'ordering': ['measurement', 'stable_key'],
            },
        ),
        migrations.AddIndex(
            model_name='occupancymeasurement',
            index=models.Index(fields=['local_date', 'captured_at'], name='occupancy_local_capture_idx'),
        ),
        migrations.AddConstraint(
            model_name='occupancymeasurement',
            constraint=models.CheckConstraint(condition=models.Q(('calculable_sector_count__lte', models.F('observed_sector_count')), ('capacity_covered_sector_count__lte', models.F('observed_sector_count'))), name='ck_occupancy_coverage_within_observed'),
        ),
        migrations.AddConstraint(
            model_name='occupancymeasurement',
            constraint=models.CheckConstraint(condition=models.Q(('occupancy_percentage__gte', 0), ('occupancy_percentage__isnull', True), _connector='OR'), name='ck_occupancy_percentage_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='occupancygroupmeasurement',
            constraint=models.UniqueConstraint(fields=('measurement', 'stable_key'), name='uq_occupancy_group_measurement_key'),
        ),
        migrations.AddConstraint(
            model_name='occupancygroupmeasurement',
            constraint=models.CheckConstraint(condition=models.Q(('official_capacity__gt', 0), ('official_capacity__isnull', True), _connector='OR'), name='ck_occupancy_group_capacity_positive'),
        ),
        migrations.AddConstraint(
            model_name='occupancygroupmeasurement',
            constraint=models.CheckConstraint(condition=models.Q(('occupancy_percentage__gte', 0), ('occupancy_percentage__isnull', True), _connector='OR'), name='ck_occupancy_group_percentage_nonnegative'),
        ),
    ]
