# Generated by Django 5.2.13 on 2026-08-17 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0016_occupancy_measurement'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyOccupancySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_date', models.DateField(help_text='Local calendar date (America/Bahia) of the summarized measurements', unique=True)),
                ('algorithm_version', models.CharField(max_length=30)),
                ('measurement_count', models.PositiveIntegerField()),
                ('first_captured_at', models.DateTimeField()),
                ('last_captured_at', models.DateTimeField()),
                ('known_capacity', models.PositiveIntegerField()),
                ('calculable_capacity', models.PositiveIntegerField()),
                ('mean_occupied', models.DecimalField(decimal_places=2, max_digits=12)),
                ('min_occupied', models.PositiveIntegerField()),
                ('max_occupied', models.PositiveIntegerField()),
                ('mean_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_exceeded_by', models.PositiveIntegerField(blank=True, null=True)),
                ('min_observed_sector_count', models.PositiveIntegerField()),
                ('max_observed_sector_count', models.PositiveIntegerField()),
                ('min_capacity_covered_sector_count', models.PositiveIntegerField()),
                ('max_capacity_covered_sector_count', models.PositiveIntegerField()),
                ('min_calculable_sector_count', models.PositiveIntegerField()),
                ('max_calculable_sector_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_summaries', to='census.capacitycatalogversion')),
            ],
            options={
                'verbose_name': 'Daily Occupancy Summary',
                'verbose_name_plural': 'Daily Occupancy Summaries',
                'ordering': ['local_date'],
            },
        ),
        migrations.CreateModel(
            name='DailyGroupOccupancySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_key', models.CharField(max_length=100)),
                ('display_name', models.CharField(max_length=255)),
                ('calculation_policy', models.CharField(blank=True, default='', max_length=30)),
                ('calculation_status', models.CharField(choices=[('calculated', 'Calculated'), ('linked_slots_pending', 'Linked slots pending'), ('unrated', 'Unrated'), ('unmapped', 'Unmapped')], max_length=30)),
                ('official_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('measurement_count', models.PositiveIntegerField()),
                ('first_captured_at', models.DateTimeField()),
                ('last_captured_at', models.DateTimeField()),
                ('mean_occupied', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_occupied', models.PositiveIntegerField(blank=True, null=True)),
                ('max_occupied', models.PositiveIntegerField(blank=True, null=True)),
                ('mean_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_exceeded_by', models.PositiveIntegerField(blank=True, null=True)),
                ('daily_summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='census.dailyoccupancysummary')),
            ],
            options={
                'verbose_name': 'Daily Group Occupancy Summary',
                'verbose_name_plural': 'Daily Group Occupancy Summaries',
                'ordering': ['daily_summary', 'stable_key'],
            },
        ),
        migrations.AddConstraint(
            model_name='dailyoccupancysummary',
            constraint=models.CheckConstraint(condition=models.Q(('first_captured_at__lte', models.F('last_captured_at'))), name='ck_daily_summary_capture_bounds_ordered'),
        ),
        migrations.AddConstraint(
            model_name='dailyoccupancysummary',
            constraint=models.CheckConstraint(condition=models.Q(('min_observed_sector_count__lte', models.F('max_observed_sector_count')), ('min_capacity_covered_sector_count__lte', models.F('max_capacity_covered_sector_count')), ('min_calculable_sector_count__lte', models.F('max_calculable_sector_count'))), name='ck_daily_summary_coverage_bounds_ordered'),
        ),
        migrations.AddConstraint(
            model_name='dailyoccupancysummary',
            constraint=models.CheckConstraint(condition=models.Q(('mean_occupied__gte', 0)), name='ck_daily_summary_mean_occupied_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='dailyoccupancysummary',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mean_percentage__gte', 0), ('mean_percentage__isnull', True), _connector='OR'), models.Q(('min_percentage__gte', 0), ('min_percentage__isnull', True), _connector='OR'), models.Q(('max_percentage__gte', 0), ('max_percentage__isnull', True), _connector='OR')), name='ck_daily_summary_percentages_valid'),
        ),
        migrations.AddConstraint(
            model_name='dailygroupoccupancysummary',
            constraint=models.UniqueConstraint(fields=('daily_summary', 'stable_key'), name='uq_daily_group_summary_key'),
        ),
        migrations.AddConstraint(
            model_name='dailygroupoccupancysummary',
            constraint=models.CheckConstraint(condition=models.Q(('first_captured_at__lte', models.F('last_captured_at'))), name='ck_daily_group_capture_bounds_ordered'),
        ),
        migrations.AddConstraint(
            model_name='dailygroupoccupancysummary',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mean_occupied__gte', 0), ('mean_occupied__isnull', True), _connector='OR'), models.Q(('min_occupied__gte', 0), ('min_occupied__isnull', True), _connector='OR'), models.Q(('max_occupied__gte', 0), ('max_occupied__isnull', True), _connector='OR')), name='ck_daily_group_occupied_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='dailygroupoccupancysummary',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('mean_percentage__gte', 0), ('mean_percentage__isnull', True), _connector='OR'), models.Q(('min_percentage__gte', 0), ('min_percentage__isnull', True), _connector='OR'), models.Q(('max_percentage__gte', 0), ('max_percentage__isnull', True), _connector='OR')), name='ck_daily_group_percentages_valid'),
        ),
        migrations.AddConstraint(
            model_name='dailygroupoccupancysummary',
            constraint=models.CheckConstraint(condition=models.Q(('official_capacity__gt', 0), ('official_capacity__isnull', True), _connector='OR'), name='ck_daily_group_capacity_positive'),
        ),
    ]
