# Generated by Django 5.2.13 on 2026-08-20 (CCO3A-S1)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "census",
            "0017_dailyoccupancysummary_dailygroupoccupancysummary_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="censussnapshot",
            name="age_band",
            field=models.CharField(
                choices=[
                    ("under_12", "Under 12"),
                    ("age_12_or_over", "Age 12 or over"),
                    ("unknown", "Unknown"),
                    ("not_applicable", "Not applicable"),
                ],
                default="unknown",
                help_text=(
                    "Normalized occupancy age band derived from the legacy "
                    "Idade column; raw age is never persisted"
                ),
                max_length=20,
            ),
        ),
    ]
