# Generated by Django 5.2.13 on 2026-08-20 (CCO3A-S2)

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0018_censussnapshot_age_band"),
    ]

    operations = [
        migrations.AddField(
            model_name="capacitysectormembership",
            name="age_selector",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("under_12", "Under 12"),
                    ("age_12_or_over", "Age 12 or over"),
                ],
                default="all",
                help_text=(
                    "Which census rows of this source code belong to this "
                    "group: all rows or one exclusive age partition"
                ),
                max_length=20,
            ),
        ),
        migrations.RemoveConstraint(
            model_name="capacitysectormembership",
            name="uq_capacity_member_catalog_source_code",
        ),
        migrations.AddConstraint(
            model_name="capacitysectormembership",
            constraint=models.UniqueConstraint(
                fields=("catalog", "source_code", "age_selector"),
                name="uq_capacity_member_catalog_code_selector",
            ),
        ),
    ]
