# Generated by Django 5.2.13 on 2026-08-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0019_membership_age_selector'),
        ('ingestion', '0005_add_worker_heartbeat'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailyoccupancysummary',
            name='ck_daily_summary_mean_occupied_nonnegative',
        ),
        migrations.AddField(
            model_name='dailyoccupancysummary',
            name='age_excluded_measurement_count',
            field=models.PositiveIntegerField(default=0, help_text='Day measurements excluded from official statistics because their occupancy-v2 point rate is partial'),
        ),
        migrations.AddField(
            model_name='dailyoccupancysummary',
            name='eligible_measurement_count',
            field=models.PositiveIntegerField(default=0, help_text='Day measurements eligible for official statistics; age-partial occupancy-v2 measurements are never eligible'),
        ),
        migrations.AddField(
            model_name='dailyoccupancysummary',
            name='official_calculable_sector_count',
            field=models.PositiveIntegerField(blank=True, help_text="Official calculable sectors of the day's catalog (occupancy-v2 only); null keeps occupancy-v1 summaries uninterpreted", null=True),
        ),
        migrations.AddField(
            model_name='dailyoccupancysummary',
            name='official_sector_count',
            field=models.PositiveIntegerField(blank=True, help_text="Official sectors of the day's catalog (occupancy-v2 only); null keeps occupancy-v1 summaries uninterpreted", null=True),
        ),
        migrations.AddField(
            model_name='occupancymeasurement',
            name='age_partial',
            field=models.BooleanField(default=False, help_text='True when this occupancy-v2 measurement omitted occupied rows of an age-partitioned sector because their normalized age band is unknown; such measurements are excluded from official daily statistics'),
        ),
        migrations.AddField(
            model_name='occupancymeasurement',
            name='official_calculable_sector_count',
            field=models.PositiveIntegerField(blank=True, help_text='Official sectors with calculable occupancy (occupancy-v2 only); null keeps occupancy-v1 uninterpreted', null=True),
        ),
        migrations.AddField(
            model_name='occupancymeasurement',
            name='official_capacity_sector_count',
            field=models.PositiveIntegerField(blank=True, help_text='Official sectors with declared capacity (occupancy-v2 only); null keeps occupancy-v1 uninterpreted', null=True),
        ),
        migrations.AddField(
            model_name='occupancymeasurement',
            name='official_sector_count',
            field=models.PositiveIntegerField(blank=True, help_text='Official sectors of the applicable catalog (occupancy-v2 only); null keeps occupancy-v1 uninterpreted', null=True),
        ),
        migrations.AddField(
            model_name='occupancymeasurement',
            name='unknown_age_count',
            field=models.PositiveIntegerField(default=0, help_text='Aggregate count of occupied rows of age-partitioned sectors whose normalized age band is unknown; no row-level patient data is ever stored here'),
        ),
        migrations.AlterField(
            model_name='dailyoccupancysummary',
            name='max_occupied',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailyoccupancysummary',
            name='mean_occupied',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='dailyoccupancysummary',
            name='min_occupied',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='dailyoccupancysummary',
            constraint=models.CheckConstraint(condition=models.Q(('mean_occupied__gte', 0), ('mean_occupied__isnull', True), _connector='OR'), name='ck_daily_summary_mean_occupied_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='occupancymeasurement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('age_partial', True), ('unknown_age_count__gt', 0)), models.Q(('age_partial', False), ('unknown_age_count', 0)), _connector='OR'), name='ck_occupancy_age_partial_consistent'),
        ),
        migrations.AddConstraint(
            model_name='occupancymeasurement',
            constraint=models.CheckConstraint(condition=models.Q(('official_sector_count__isnull', True), models.Q(('official_calculable_sector_count__lte', models.F('official_capacity_sector_count')), ('official_capacity_sector_count__lte', models.F('official_sector_count'))), _connector='OR'), name='ck_occupancy_official_coverage_ordered'),
        ),
    ]
