# Generated by Django 5.2.13 on 2026-08-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0020_remove_dailyoccupancysummary_ck_daily_summary_mean_occupied_nonnegative_and_more'),
        ('ingestion', '0005_add_worker_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitycatalogversion',
            name='algorithm_version',
            field=models.CharField(blank=True, help_text='Immutable occupancy algorithm context declared by the published document; null keeps legacy structural dispatch to v1/v2', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dailyoccupancysummary',
            name='position_excluded_measurement_count',
            field=models.PositiveIntegerField(default=0, help_text='Day measurements excluded from official statistics because their occupancy-v3 point rate is physically partial; may overlap with the age reason count'),
        ),
        migrations.AddField(
            model_name='occupancygroupmeasurement',
            name='official_availability',
            field=models.PositiveIntegerField(blank=True, help_text='Nonnegative official availability balance for calculable occupancy-v3 groups; null keeps v1/v2 and non-calculable groups uninterpreted', null=True),
        ),
        migrations.AddField(
            model_name='occupancymeasurement',
            name='official_availability',
            field=models.PositiveIntegerField(blank=True, help_text='Sum of nonnegative group availability balances computed without cross-sector compensation (occupancy-v3 only); null keeps v1/v2 uninterpreted', null=True),
        ),
        migrations.AddField(
            model_name='occupancymeasurement',
            name='physical_reconciliation_json',
            field=models.JSONField(blank=True, default=None, help_text='Closed aggregate reconciliation of raw rows, physical positions, duplicates, conflicts and unidentified rows (occupancy-v3 only); contains only allowlisted nonnegative integers, never row-level identity', null=True),
        ),
        migrations.AddField(
            model_name='occupancymeasurement',
            name='position_partial',
            field=models.BooleanField(blank=True, help_text='True when this occupancy-v3 measurement excluded occupied rows because of conflicting physical positions or occupied rows without usable bed identity; null keeps v1/v2 uninterpreted', null=True),
        ),
        migrations.AddConstraint(
            model_name='occupancymeasurement',
            constraint=models.CheckConstraint(condition=models.Q(('position_partial__isnull', True), ('algorithm_version', 'occupancy-v3'), _connector='OR'), name='ck_occupancy_position_partial_only_v3'),
        ),
        migrations.AddConstraint(
            model_name='occupancymeasurement',
            constraint=models.CheckConstraint(condition=models.Q(('official_availability__gte', 0), ('official_availability__isnull', True), _connector='OR'), name='ck_occupancy_availability_nonnegative'),
        ),
    ]
