# Generated by Django 5.2.13 on 2026-08-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0021_capacitycatalogversion_algorithm_version_and_more'),
        ('ingestion', '0005_add_worker_heartbeat'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyoccupancysummary',
            name='quality_warning_measurement_count',
            field=models.PositiveIntegerField(default=0, help_text='Day measurements materialized under occupancy-v4 that carry quality warnings; every v4 measurement stays eligible and v4 warnings never increment the historical exclusion counters'),
        ),
        migrations.AddField(
            model_name='occupancymeasurement',
            name='quality_warning',
            field=models.BooleanField(blank=True, default=None, help_text='True when this occupancy-v4 measurement carries actionable quality warnings (conflicts, occupied rows without position, unknown or divergent partition age, or occupied unmapped positions); such measurements stay daily-eligible with a separate warning counter. Null keeps v1-v3 uninterpreted.', null=True),
        ),
        migrations.AlterField(
            model_name='occupancymeasurement',
            name='physical_reconciliation_json',
            field=models.JSONField(blank=True, default=None, help_text='Closed aggregate reconciliation of raw rows, physical positions, duplicates, conflicts and unidentified rows (occupancy-v3 uses schema 1, occupancy-v4 uses schema 2); contains only allowlisted nonnegative integers, never row-level identity', null=True),
        ),
        migrations.AddConstraint(
            model_name='occupancymeasurement',
            constraint=models.CheckConstraint(condition=models.Q(('quality_warning__isnull', True), ('algorithm_version', 'occupancy-v4'), _connector='OR'), name='ck_occupancy_quality_warning_only_v4'),
        ),
    ]
