# Generated by Django 5.2.13 on 2026-08-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0022_dailyoccupancysummary_quality_warning_measurement_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitysectormembership',
            name='source_display_name',
            field=models.CharField(blank=True, help_text='Curated human-facing alias for this source code in this version; null keeps historical catalogs unaliased; schema 3.0 documents require a non-empty value', max_length=255, null=True),
        ),
    ]
