# Generated by Django 5.2.13 on 2026-04-25 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_identity_key', models.CharField(max_length=512)),
                ('content_hash', models.CharField(max_length=128)),
                ('happened_at', models.DateTimeField()),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('author_name', models.CharField(max_length=512)),
                ('profession_type', models.CharField(max_length=100)),
                ('content_text', models.TextField()),
                ('signature_line', models.CharField(blank=True, default='', max_length=512)),
                ('raw_payload_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='patients.admission')),
                ('ingestion_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='ingestion.ingestionrun')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='patients.patient')),
            ],
            options={
                'ordering': ['-happened_at'],
                'constraints': [models.UniqueConstraint(fields=('event_identity_key', 'content_hash'), name='uq_evt_identity')],
            },
        ),
    ]
