# DSRS-S2: materialized daily statistics revision, its copied official closing
# sectors and the nominal closing-census patients. Additive initial migration
# only: no RunPython, no data migration and no historical backfill.
#
# Generated by Django 5.2.13 on 2026-09-24 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('census', '0024_occupancy_quality_warning_v4_v5'),
        ('ingestion', '0006_evolutionextractioncoverage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatisticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_date', models.DateField(help_text='Local calendar date (America/Bahia) this revision reports')),
                ('revision', models.PositiveIntegerField(default=1, help_text='1-based revision of this local date, increasing over time')),
                ('status', models.CharField(choices=[('ready', 'Ready'), ('superseded', 'Superseded')], default='ready', help_text='Publication state of this revision', max_length=20)),
                ('activation_date', models.DateField(help_text='First eligible local date declared for the feature when this revision was materialized')),
                ('algorithm_version', models.CharField(help_text='Occupancy algorithm of the exact closing measurement', max_length=30)),
                ('source_fingerprint', models.CharField(help_text='SHA-256 of the normalized sources used by this revision; an unchanged fingerprint makes a rebuild a no-op', max_length=64)),
                ('quality_warnings_json', models.JSONField(blank=True, default=list, help_text='Structured quality warnings of the selected window, such as a missing accepted anchor census; aggregate codes only')),
                ('generated_at', models.DateTimeField(auto_now_add=True, help_text='Instant this revision was materialized')),
                ('anchor_run', models.ForeignKey(blank=True, help_text='Last accepted census before the opening photograph; null when no accepted anchor existed', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='anchored_statistics_reports', to='ingestion.ingestionrun')),
                ('catalog', models.ForeignKey(help_text='Historical catalog of the closing measurement', on_delete=django.db.models.deletion.PROTECT, related_name='daily_statistics_reports', to='census.capacitycatalogversion')),
                ('closing_run', models.ForeignKey(help_text='Accepted closing census extraction run of the day', on_delete=django.db.models.deletion.PROTECT, related_name='closed_statistics_reports', to='ingestion.ingestionrun')),
                ('measurement', models.ForeignKey(help_text='Exact immutable closing measurement this revision copies', on_delete=django.db.models.deletion.PROTECT, related_name='daily_statistics_reports', to='census.occupancymeasurement')),
                ('opening_run', models.ForeignKey(help_text='Accepted opening census extraction run of the day', on_delete=django.db.models.deletion.PROTECT, related_name='opened_statistics_reports', to='ingestion.ingestionrun')),
            ],
            options={
                'verbose_name': 'Daily Statistics Report',
                'verbose_name_plural': 'Daily Statistics Reports',
                'ordering': ['local_date', 'revision'],
            },
        ),
        migrations.CreateModel(
            name='DailyStatisticsSector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stable_key', models.CharField(help_text='Historical stable official key of the group', max_length=100)),
                ('display_name', models.CharField(help_text='Historical display name of the group', max_length=255)),
                ('calculation_policy', models.CharField(blank=True, default='', max_length=30)),
                ('calculation_status', models.CharField(choices=[('calculated', 'Calculated'), ('linked_slots_pending', 'Linked slots pending'), ('unrated', 'Unrated'), ('unmapped', 'Unmapped')], max_length=30)),
                ('official_capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('occupied_count', models.PositiveIntegerField(blank=True, null=True)),
                ('occupancy_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('exceeded_by', models.PositiveIntegerField(blank=True, null=True)),
                ('official_availability', models.PositiveIntegerField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='statistics_reports.dailystatisticsreport')),
            ],
            options={
                'verbose_name': 'Daily Statistics Sector',
                'verbose_name_plural': 'Daily Statistics Sectors',
                'ordering': ['report', 'stable_key'],
            },
        ),
        migrations.CreateModel(
            name='DailyStatisticsPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bed', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=512)),
                ('record', models.CharField(max_length=255)),
                ('specialty', models.CharField(blank=True, default='', max_length=100)),
                ('census_snapshot', models.ForeignKey(help_text='Exact closing census row this patient was copied from', on_delete=django.db.models.deletion.PROTECT, related_name='daily_statistics_patients', to='census.censussnapshot')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='statistics_reports.dailystatisticsreport')),
                ('sector', models.ForeignKey(blank=True, help_text='Official grouping of the closing census; null keeps a safely unidentified grouping explicit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='statistics_reports.dailystatisticssector')),
            ],
            options={
                'verbose_name': 'Daily Statistics Patient',
                'verbose_name_plural': 'Daily Statistics Patients',
                'ordering': ['report', 'sector', 'census_snapshot'],
            },
        ),
        migrations.AddIndex(
            model_name='dailystatisticsreport',
            index=models.Index(fields=['local_date', 'status'], name='dsr_date_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='dailystatisticsreport',
            constraint=models.UniqueConstraint(fields=('local_date', 'revision'), name='uq_daily_statistics_report_date_revision'),
        ),
        migrations.AddConstraint(
            model_name='dailystatisticsreport',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'ready')), fields=('local_date',), name='uq_daily_statistics_report_current_ready'),
        ),
        migrations.AddConstraint(
            model_name='dailystatisticsreport',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='ck_daily_statistics_report_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='dailystatisticsreport',
            constraint=models.CheckConstraint(condition=models.Q(('local_date__gte', models.F('activation_date'))), name='ck_daily_statistics_report_after_activation'),
        ),
        migrations.AddConstraint(
            model_name='dailystatisticssector',
            constraint=models.UniqueConstraint(fields=('report', 'stable_key'), name='uq_daily_statistics_sector_report_key'),
        ),
        migrations.AddConstraint(
            model_name='dailystatisticspatient',
            constraint=models.UniqueConstraint(fields=('report', 'census_snapshot'), name='uq_daily_statistics_patient_report_snapshot'),
        ),
    ]
