# DSRS-S3: detected entries and internal transfers of one daily revision. One
# durable row per logical fact, with its versioned origin classification, its
# detection interval and its deterministic fingerprint. Additive migration
# only: no RunPython, no data migration and no historical backfill.
#
# Generated by Django 5.2.13 on 2026-09-24 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0024_occupancy_quality_warning_v4_v5'),
        ('statistics_reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatisticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('hospital_admission', 'Internação hospitalar'), ('internal_transfer', 'Transferência interna'), ('unclassified_entry', 'Entrada no setor — origem não identificada')], help_text='Stable normalized kind of the detected fact', max_length=30)),
                ('origin_nature', models.CharField(choices=[('external', 'Externa ao hospital'), ('hospital_internal', 'Interna ao hospital'), ('unknown', 'Não identificada')], default='unknown', help_text='Institutional nature attributed to the event origin', max_length=30)),
                ('origin_value', models.CharField(blank=True, default='', help_text='Normalized source origin value the classification used; empty when the origin came from a census position instead', max_length=100)),
                ('origin_policy_version', models.CharField(help_text='Version of the origin policy in force when this event was derived; stored for audit even when the origin came from a resolved census position', max_length=30)),
                ('record', models.CharField(help_text='Normalized patient record of the detecting row', max_length=255)),
                ('name', models.CharField(help_text='Nominal patient name at detection time', max_length=512)),
                ('bed', models.CharField(help_text='Bed of the detecting row', max_length=50)),
                ('occurred_at', models.DateTimeField(blank=True, help_text='Exact aware clinical instant when the source provides one; null never synthesizes an hour', null=True)),
                ('occurred_on', models.DateField(blank=True, help_text='Clinical date when only a date exists, without an hour; null never synthesizes a clinical date', null=True)),
                ('detected_not_before', models.DateTimeField(help_text='Instant of the accepted census photograph before the change')),
                ('detected_at', models.DateTimeField(help_text='Instant of the accepted census photograph detecting the change')),
                ('fingerprint', models.CharField(help_text='Deterministic SHA-256 identity of this detected fact inside its revision', max_length=64)),
                ('census_snapshot', models.ForeignKey(help_text='Detecting census row this event was observed on', on_delete=django.db.models.deletion.PROTECT, related_name='daily_statistics_events', to='census.censussnapshot')),
                ('destination_sector', models.ForeignKey(blank=True, help_text='Official grouping the patient reached; null keeps an unidentified destination explicit instead of inventing it', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_events', to='statistics_reports.dailystatisticssector')),
                ('origin_sector', models.ForeignKey(blank=True, help_text='Official grouping the patient left; null keeps an unidentified origin explicit instead of inventing it', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_events', to='statistics_reports.dailystatisticssector')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='statistics_reports.dailystatisticsreport')),
            ],
            options={
                'verbose_name': 'Daily Statistics Event',
                'verbose_name_plural': 'Daily Statistics Events',
                'ordering': ['report', 'detected_at', 'pk'],
                'indexes': [models.Index(fields=['report', 'kind'], name='dse_report_kind_idx'), models.Index(fields=['report', 'origin_sector'], name='dse_report_origin_idx'), models.Index(fields=['report', 'destination_sector'], name='dse_report_dest_idx')],
                'constraints': [models.UniqueConstraint(fields=('report', 'fingerprint'), name='uq_daily_statistics_event_report_fingerprint'), models.CheckConstraint(condition=models.Q(('origin_sector__isnull', False), ('destination_sector__isnull', False), _connector='OR'), name='ck_daily_statistics_event_has_endpoint'), models.CheckConstraint(condition=models.Q(('detected_at__gte', models.F('detected_not_before'))), name='ck_daily_statistics_event_detection_order')],
            },
        ),
    ]
