# DSRS-S4: sector attribution of one detected event plus the endpoint
# constraint of an exit. The endpoint requirement is kept for entries and
# transfers -- a death, an effective hospital discharge or an unclassified
# departure may stay without any sector when no unambiguous earlier census
# position existed. The exceptional third round of the slice also persists the
# inspectable provenance of the chosen clinical evidence row as two nullable
# scalar columns (source kind and primary key, no foreign key and no clinical
# payload). Additive migration only: no RunPython, no data migration and no
# historical backfill.
#
# Generated by Django 5.2.13 on 2026-09-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0024_occupancy_quality_warning_v4_v5'),
        ('statistics_reports', '0002_statistics_events'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dailystatisticsevent',
            name='ck_daily_statistics_event_has_endpoint',
        ),
        migrations.AddField(
            model_name='dailystatisticsevent',
            name='sector_attribution',
            field=models.CharField(choices=[('observed', 'Observado na fotografia de detecção'), ('inferred_last_census', 'Inferido da última posição censitária'), ('unknown', 'Não determinado')], default='observed', help_text='How the sector this event stores was determined: observed in the detecting photograph, inferred from the last unambiguous census position when the event itself carries no sector, or not determined', max_length=30),
        ),
        migrations.AddField(
            model_name='dailystatisticsevent',
            name='source_kind',
            field=models.CharField(blank=True, help_text='Stable source kind of the clinical exit evidence that explained this event (e.g. death_record); null when only the census photographs proved it, so no evidence is ever claimed', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='dailystatisticsevent',
            name='source_pk',
            field=models.BigIntegerField(blank=True, help_text='Primary key of that clinical evidence row, kept as an inspectable provenance reference without a foreign key; null when no clinical evidence explained this event', null=True),
        ),
        migrations.AlterField(
            model_name='dailystatisticsevent',
            name='kind',
            field=models.CharField(choices=[('hospital_admission', 'Internação hospitalar'), ('internal_transfer', 'Transferência interna'), ('death', 'Óbito'), ('hospital_discharge', 'Alta hospitalar'), ('unclassified_entry', 'Entrada no setor — origem não identificada'), ('unclassified_departure', 'Saída do setor — destino não identificado')], help_text='Stable normalized kind of the detected fact', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='dailystatisticsevent',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ('death', 'hospital_discharge', 'unclassified_departure')), ('origin_sector__isnull', False), ('destination_sector__isnull', False), _connector='OR'), name='ck_daily_statistics_event_has_endpoint'),
        ),
    ]
