# DSRS-S6: the dedicated permissions of the daily statistics report. The
# consultation permission protects the page and the sidebar item, and the
# export permission protects the workbook served by DSRS-S7; authentication
# alone is insufficient for both. Additive options-only migration: no
# RunPython, no data migration and no historical backfill.
#
# Generated by Django 5.2.13 on 2026-09-25 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("statistics_reports", "0003_event_revision_constraints"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dailystatisticsreport",
            options={
                "ordering": ["local_date", "revision"],
                "permissions": [
                    (
                        "view_daily_statistics",
                        "Can view the daily statistics report",
                    ),
                    (
                        "export_daily_statistics",
                        "Can export the daily statistics report",
                    ),
                ],
                "verbose_name": "Daily Statistics Report",
                "verbose_name_plural": "Daily Statistics Reports",
            },
        ),
    ]
