# Generated by Django 5.2.13 on 2026-10-10 13:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_reports', '0006_statistics_export_log_file_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='statisticsexportlog',
            name='report',
            field=models.ForeignKey(help_text='Exact revision the served archive reproduced', on_delete=django.db.models.deletion.PROTECT, related_name='export_logs', to='statistics_reports.dailystatisticsreport'),
        ),
        migrations.AlterField(
            model_name='statisticsexportlog',
            name='served_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Instant the archive was generated and ready to be served'),
        ),
        migrations.AlterField(
            model_name='statisticsexportlog',
            name='user',
            field=models.ForeignKey(help_text='Authenticated user the archive was served to', on_delete=django.db.models.deletion.PROTECT, related_name='daily_statistics_exports', to=settings.AUTH_USER_MODEL),
        ),
    ]
