# Generated by Django 5.2.13 on 2026-04-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=20)),
                ('events_processed', models.PositiveIntegerField(default=0)),
                ('events_created', models.PositiveIntegerField(default=0)),
                ('events_skipped', models.PositiveIntegerField(default=0)),
                ('events_revised', models.PositiveIntegerField(default=0)),
                ('admissions_seen', models.PositiveIntegerField(default=0)),
                ('admissions_created', models.PositiveIntegerField(default=0)),
                ('admissions_updated', models.PositiveIntegerField(default=0)),
                ('parameters_json', models.JSONField(blank=True, default=dict)),
                ('gaps_json', models.JSONField(blank=True, default=list, help_text='List of gap windows that were extracted in this run.')),
                ('error_message', models.TextField(blank=True, default='')),
                ('intent', models.CharField(blank=True, default='', help_text='Operational intent of this run (e.g. admissions_only).', max_length=50)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
