# Generated by Django 5.2.13 on 2026-04-26 12:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionrun',
            name='failure_reason',
            field=models.CharField(blank=True, choices=[('', 'None'), ('timeout', 'Timeout'), ('source_unavailable', 'Source Unavailable'), ('invalid_payload', 'Invalid Payload'), ('unexpected_exception', 'Unexpected Exception'), ('validation_error', 'Validation Error')], default='', help_text='Normalized failure category for operational analysis.', max_length=50),
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='queued_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='timed_out',
            field=models.BooleanField(default=False, help_text='Whether this run terminated due to timeout.'),
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='worker_label',
            field=models.CharField(blank=True, default='', help_text='Optional worker identifier for diagnostics.', max_length=100),
        ),
    ]
