# Generated by Django 5.2.13 on 2026-04-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_alter_ingestionrun_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionrun',
            name='gaps_json',
            field=models.JSONField(blank=True, default=list, help_text='List of gap windows that were extracted in this run.'),
        ),
    ]
