# Generated by Django 5.2.13 on 2026-04-26 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0002_expand_ingestion_run_lifecycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRunStageMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=50)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='succeeded', max_length=20)),
                ('details_json', models.JSONField(blank=True, default=dict, help_text='Optional stage-level context (counters, gaps count, etc.).')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_metrics', to='ingestion.ingestionrun')),
            ],
            options={
                'ordering': ['started_at'],
                'indexes': [models.Index(fields=['run', 'stage_name'], name='ingestion_i_run_id_d987d2_idx'), models.Index(fields=['stage_name', 'status'], name='ingestion_i_stage_n_aba1c2_idx')],
            },
        ),
    ]
