# Generated by Django 5.2.13 on 2026-04-22 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_ingestionrun_gaps_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionrun',
            name='admissions_created',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='admissions_seen',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='admissions_updated',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
