# Generated by Django 5.2.13 on 2026-04-30 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0003_create_stage_metric'),
    ]

    operations = [
        migrations.CreateModel(
            name='CensusExecutionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('enqueue_finished_at', models.DateTimeField(blank=True, help_text='Moment when all initial runs were enqueued.', null=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='Moment when the batch was fully drained.', null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=20)),
                ('notes_json', models.JSONField(blank=True, default=dict, help_text='Optional batch-level context (snapshot_id, counts, etc.).')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='Number of execution attempts so far (starts at 0).'),
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='max_attempts',
            field=models.PositiveSmallIntegerField(default=3, help_text='Maximum execution attempts before final failure.'),
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='next_retry_at',
            field=models.DateTimeField(blank=True, help_text='Earliest datetime for the next retry attempt.', null=True),
        ),
        migrations.AddField(
            model_name='ingestionrun',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Census execution batch this run belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='ingestion.censusexecutionbatch'),
        ),
        migrations.CreateModel(
            name='FinalRunFailure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_record', models.CharField(help_text='Patient identifier from the source system.', max_length=100)),
                ('intent', models.CharField(help_text='Operational intent that failed (e.g. admissions_only).', max_length=50)),
                ('failed_at', models.DateTimeField(auto_now_add=True)),
                ('attempts_exhausted', models.PositiveSmallIntegerField(help_text='Total attempts tried before this final failure.')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_failures', to='ingestion.censusexecutionbatch')),
                ('run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_failure', to='ingestion.ingestionrun')),
            ],
            options={
                'ordering': ['-failed_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestionRunAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveSmallIntegerField(help_text='1-based attempt index (1, 2, or 3).')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], default='succeeded', max_length=20)),
                ('failure_reason', models.CharField(blank=True, choices=[('', 'None'), ('timeout', 'Timeout'), ('source_unavailable', 'Source Unavailable'), ('invalid_payload', 'Invalid Payload'), ('unexpected_exception', 'Unexpected Exception'), ('validation_error', 'Validation Error')], default='', help_text='Normalized failure category for this attempt.', max_length=50)),
                ('timed_out', models.BooleanField(default=False, help_text='Whether this attempt terminated due to timeout.')),
                ('error_message', models.TextField(blank=True, default='', help_text='Free-text error context for this attempt.')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='ingestion.ingestionrun')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
    ]
