# Generated by Django 5.2.13 on 2026-04-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_ingestionrun_admission_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionrun',
            name='intent',
            field=models.CharField(blank=True, default='', help_text='Operational intent of this run (e.g. admissions_only).', max_length=50),
        ),
    ]
