# Generated by Django 5.2.13 on 2026-06-24 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0004_add_batch_retry_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingestionrun',
            name='worker_heartbeat_at',
            field=models.DateTimeField(blank=True, help_text='Last heartbeat timestamp from the processing worker. Set when a run is claimed and refreshed periodically while the worker actively processes this run. Null before the first claim. Used by stale-recovery to distinguish a live worker from an abandoned run.', null=True),
        ),
    ]
