# Generated by Django 5.2.13 on 2026-08-30 17:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0005_add_worker_heartbeat'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionExtractionCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_system', models.CharField(default='tasy', max_length=100)),
                ('start_date', models.DateField(help_text='Inclusive chunk start date.')),
                ('end_date', models.DateField(help_text='Inclusive chunk end date.')),
                ('event_count', models.PositiveIntegerField(default=0, help_text='Aggregate number of evolutions observed in the chunk.')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the chunk was (re)confirmed as covered.')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evolution_extraction_coverage', to='patients.admission')),
                ('completed_by_run', models.ForeignKey(blank=True, help_text='Run that confirmed this coverage chunk.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evolution_coverage_commits', to='ingestion.ingestionrun')),
            ],
            options={
                'ordering': ['start_date', 'end_date'],
                'constraints': [models.UniqueConstraint(fields=('admission', 'source_system', 'start_date', 'end_date'), name='uq_eec_admission_source_bounds'), models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='ck_eec_bounds_ordered'), models.CheckConstraint(condition=models.Q(('event_count__gte', 0)), name='ck_eec_event_count_nonnegative')],
            },
        ),
    ]
