# Generated by Django 5.2.13 on 2026-04-19 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_source_key', models.CharField(max_length=255)),
                ('source_system', models.CharField(default='tasy', max_length=100)),
                ('name', models.CharField(max_length=512)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, default='', max_length=20)),
                ('mother_name', models.CharField(blank=True, default='', max_length=512)),
                ('cns', models.CharField(blank=True, default='', max_length=50)),
                ('cpf', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('source_system', 'patient_source_key'), name='uq_patient_src')],
            },
        ),
        migrations.CreateModel(
            name='PatientIdentifierHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier_type', models.CharField(max_length=100)),
                ('old_value', models.CharField(blank=True, default='', max_length=255)),
                ('new_value', models.CharField(blank=True, default='', max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingestion.ingestionrun')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_history', to='patients.patient')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_admission_key', models.CharField(max_length=255)),
                ('source_system', models.CharField(default='tasy', max_length=100)),
                ('admission_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('ward', models.CharField(blank=True, default='', max_length=100)),
                ('bed', models.CharField(blank=True, default='', max_length=50)),
                ('source_patient_reference', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient')),
            ],
            options={
                'ordering': ['-admission_date'],
                'constraints': [models.UniqueConstraint(fields=('source_system', 'source_admission_key'), name='uq_adm_src')],
            },
        ),
    ]
