# Generated by Django 5.2.13 on 2026-05-14 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyDeathCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('count', models.IntegerField(default=0)),
                ('raw_data', models.JSONField(blank=True, default=list, help_text='Raw records extracted from the CSV for this date.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Daily Death Count',
                'verbose_name_plural': 'Daily Death Counts',
                'ordering': ['-date'],
            },
        ),
    ]
