# Generated by Django 5.2.13 on 2026-05-15 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deaths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeathRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('prontuario', models.CharField(blank=True, default='', max_length=50)),
                ('nome', models.CharField(blank=True, default='', max_length=255)),
                ('data_obito', models.CharField(blank=True, default='', max_length=20)),
                ('raw_extra', models.JSONField(blank=True, default=dict, help_text='Additional fields from the source CSV.')),
                ('daily_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='deaths.dailydeathcount')),
            ],
            options={
                'verbose_name': 'Death Record',
                'verbose_name_plural': 'Death Records',
                'ordering': ['prontuario'],
            },
        ),
    ]
