# Generated by Django 5.2.13 on 2026-09-04 12:07 (RPSA-S3, additive)

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deaths', '0002_deathrecord'),
        ('patients', '0003_reconciliation_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='deathrecord',
            name='admission',
            field=models.ForeignKey(blank=True, help_text='Canonical admission linked by reconciliation (null while unresolved).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='death_evidence', to='patients.admission'),
        ),
        migrations.AddField(
            model_name='deathrecord',
            name='obito_em',
            field=models.DateTimeField(blank=True, help_text='Death datetime parsed from data_obito when the source carries a complete date and time (America/Bahia); null for date-only evidence — no hour is ever synthesized.', null=True),
        ),
        migrations.AddField(
            model_name='deathrecord',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, help_text='When the latest reconciliation attempt was applied.', null=True),
        ),
        migrations.AddField(
            model_name='deathrecord',
            name='reconciliation_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('reconciled', 'Reconciled'), ('already_reconciled', 'Already reconciled'), ('patient_not_found', 'Patient not found'), ('admission_not_found', 'Admission not found'), ('ambiguous', 'Ambiguous'), ('conflict', 'Conflict'), ('invalid_exit_datetime', 'Invalid exit datetime')], default='pending', help_text='Outcome of the latest canonical exit-reconciliation attempt.', max_length=32),
        ),
        migrations.AlterField(
            model_name='deathrecord',
            name='daily_count',
            field=models.ForeignKey(blank=True, help_text='Report-batch link (nullable since RPSA-S3: evidence survives aggregate-row deletion; snapshot rows absent from a repeated extraction are detached, never deleted).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='deaths.dailydeathcount'),
        ),
        migrations.AlterField(
            model_name='deathrecord',
            name='data_obito',
            field=models.CharField(blank=True, default='', help_text='Raw death date/time string exactly as extracted from the CSV.', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='deathrecord',
            constraint=models.CheckConstraint(condition=models.Q(('reconciliation_status__in', ('pending', 'reconciled', 'already_reconciled', 'patient_not_found', 'admission_not_found', 'ambiguous', 'conflict', 'invalid_exit_datetime'))), name='ck_deathrecord_recon_status'),
        ),
    ]
