# Generated by Django 5.2.13 on 2026-05-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discharges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydischargecount',
            name='raw_data',
            field=models.JSONField(blank=True, default=list, help_text='Patient records (prontuario, nome, data_internacao) for this day.'),
        ),
    ]
