# Generated by Django 5.2.13 on 2026-05-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discharges', '0003_dischargerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargerecord',
            name='especialidade',
            field=models.CharField(blank=True, default='', help_text='Medical specialty at discharge.', max_length=20),
        ),
        migrations.AddField(
            model_name='dischargerecord',
            name='leito',
            field=models.CharField(blank=True, default='', help_text='Bed/leito at discharge.', max_length=20),
        ),
    ]
