# Generated by Django 5.2.13 on 2026-05-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discharges', '0004_add_leito_especialidade'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dischargerecord',
            unique_together={('prontuario', 'data_internacao')},
        ),
        migrations.AddField(
            model_name='dischargerecord',
            name='alta_em',
            field=models.DateTimeField(blank=True, help_text='Datetime when the discharge was registered in the system.', null=True),
        ),
        migrations.AddField(
            model_name='dischargerecord',
            name='saida_em',
            field=models.DateTimeField(blank=True, help_text='Datetime when the patient left the hospital/bed.', null=True),
        ),
        migrations.AlterField(
            model_name='dischargerecord',
            name='leito',
            field=models.CharField(blank=True, default='', help_text='Bed/leito at discharge (without L: prefix).', max_length=20),
        ),
        migrations.AlterField(
            model_name='dischargerecord',
            name='raw_extra',
            field=models.JSONField(blank=True, default=dict, help_text='Additional fields from the source.'),
        ),
        migrations.RemoveField(
            model_name='dischargerecord',
            name='date',
        ),
    ]
